### ISSUE TITLE
There are errors when querying more than 5000

### ISSUE THREAD

**Issue by DomoYao** [dsbenghe/Novell.Directory.Ldap.NETStandard#106]
Not supported PageSize.
There are errors when querying more than 5000.

   at Novell.Directory.Ldap.LdapResponse.chkResultCode() in D:\Novell.Directory.Ldap.NETStandard-master\src\Novell.Directory.Ldap.NETStandard\LdapResponse.cs:line 460
   at Novell.Directory.Ldap.LdapSearchResults.Next() in D:\Novell.Directory.Ldap.NETStandard-master\src\Novell.Directory.Ldap.NETStandard\LdapSearchResults.cs:line 363
   at Novell.Directory.Ldap.LdapSearchResults.<GetEnumerator>d__26.MoveNext() in D:\Novell.Directory.Ldap.NETStandard-master\src\Novell.Directory.Ldap.NETStandard\LdapSearchResults.cs:line 399
   at System.Linq.Enumerable.LongCount[TSource](IEnumerable`1 source)
   at ConsoleApp1.LdapService.GetChildren(String searchBase, String groupDistinguishedName, String objectCategory, String objectClass) in D:\Novell.Directory.Ldap.NETStandard-master\ConsoleApp1\LdapService.cs:line 289
   at ConsoleApp1.LdapService.GetChildren[T](String searchBase, String groupDistinguishedName) in D:\Novell.Directory.Ldap.NETStandard-master\ConsoleApp1\LdapService.cs:line 256
   at ConsoleApp1.LdapService.GetUsersInGroups() in D:\Novell.Directory.Ldap.NETStandard-master\ConsoleApp1\LdapService.cs:line 141
   at ConsoleApp1.LdapService.GetUsersInGroup(String group) in D:\Novell.Directory.Ldap.NETStandard-master\ConsoleApp1\LdapService.cs:line 129
   at ConsoleApp1.Program.Main(String[] args) in D:\Novell.Directory.Ldap.NETStandard-master\ConsoleApp1\Program.cs:line 12

**Comment by dsbenghe** [comment]
This looks like an error coming from your ldap server e.g. not correct configuration. Check your server configuration.
