### ISSUE TITLE
NullReferenceException Encountered During Connection Disposal If SecureSocketLayer Set to True After Connecting

### ISSUE THREAD

**Issue by AlliterativeAlice** [dsbenghe/Novell.Directory.Ldap.NETStandard#108]
Example of code that causes this exception:

```csharp
using (LdapConnection cn = new LdapConnection())
 {
    cn.Connect("ldap.forumsys.com", 389);
    cn.SecureSocketLayer = true;
}
```

The exception is as follows:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Novell.Directory.Ldap.Connection.Destroy(String reason, Int32 semaphoreId, InterThreadException notifyUser) in D:\Documents\Novell.Directory.Ldap.NETStandard\src\Novell.Directory.Ldap.NETStandard\Connection.cs:line 869
   at Novell.Directory.Ldap.Connection.DestroyClone() in D:\Documents\Novell.Directory.Ldap.NETStandard\src\Novell.Directory.Ldap.NETStandard\Connection.cs:line 661
   at Novell.Directory.Ldap.LdapConnection.DisconnectImpl() in D:\Documents\Novell.Directory.Ldap.NETStandard\src\Novell.Directory.Ldap.NETStandard\LdapConnection.cs:line 1606
   at Novell.Directory.Ldap.LdapConnection.Dispose(Boolean isDisposing) in D:\Documents\Novell.Directory.Ldap.NETStandard\src\Novell.Directory.Ldap.NETStandard\LdapConnection.cs:line 921
   at Novell.Directory.Ldap.LdapConnection.Dispose() in D:\Documents\Novell.Directory.Ldap.NETStandard\src\Novell.Directory.Ldap.NETStandard\LdapConnection.cs:line 462
   at NovellTest.Program.Main(String[] args) in C:\Users\amackel\source\repos\NovellTest\NovellTest\Program.cs:line 14
```

The NullReferenceException is thrown because whether to dispose `_sock` or `_socket` is based on the value of `Ssl`, which can change after the connection is opened and `_sock` or `_socket` are set.

I will submit a pull request to fix this issue by always disposing `_sock` and `_socket` if they are set, and never disposing them if they are not.

**Comment by dsbenghe** [comment]
close as the fix was merged
