### ISSUE TITLE
NullReferenceException when using SSL connection

### ISSUE THREAD

**Issue by pawod** [dsbenghe/Novell.Directory.Ldap.NETStandard#19]
When setting `connection.SecureSocketLayer = true;` calling `connection.Bind(...)` throws a `NullReferenceException`.

- HResult: -2147467261
- _xcode: -532462766
- Stacktrace:

```
at Novell.Directory.Ldap.Connection.Destroy(String reason, Int32 semaphoreId, InterThreadException notifyUser)

at Novell.Directory.Ldap.Connection.destroyClone()

at Novell.Directory.Ldap.LdapConnection.Dispose(Boolean isDisposing)
```

**Comment by pawod** [comment]
I was setting the property AFTER connecting. Doing it the other way round solved it.
