### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by ExtSolTech** [dsbenghe/Novell.Directory.Ldap.NETStandard#210]
This code is working on Windows but not working on Android 11.0 - API 30

Here is my example code:

```
Text = "-";
var manager = new LdapManager("doamin.com", true);

try
{
    bool result = await manager.ConnectAsync("userDomain\\userName", "userPassword");
    Text = result.ToString();
}
catch(Exception ex)
{
    Text = ex.ToString();
}

public class LdapManager
{
    public readonly string DomainName;
    public readonly bool EnableSSL;

    LdapConnection connection;

    public LdapManager(string domainName, bool enableSSL)
    {
        DomainName = domainName;
        EnableSSL = enableSSL;
    }

    public async Task<bool> ConnectAsync(string userId, string password)
    {
        if (connection != null)
            throw new Exception(nameof(ConnectAsync));

        return await Task.Run(() =>
        {
            connection = new LdapConnection();
            connection.SecureSocketLayer = EnableSSL;
            connection.Connect(DomainName, EnableSSL ? LdapConnection.DEFAULT_SSL_PORT : LdapConnection.DEFAULT_PORT);
            connection.Bind(userId, password);
            return connection.Bound;
        });
    }
}

```

**The error occurred when Connect method called. The error message is:**
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   --- End of inner exception stack trace ---
   at Novell.Directory.Ldap.AsyncExtensions.WaitAndUnwrap(Task task, Int32 timeout)
   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port, Int32 semaphoreId)
   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port)
   at Novell.Directory.Ldap.LdapConnection.Connect(String host, Int32 port)
   at WitturToolsApp.UserInterface.ViewModels.LdapManager.<>c__DisplayClass4_0.<ConnectAsync>b__0() in C:\WitturRepos\IndicatorNumbers\Source\WitturToolsApp\UserInterface\ViewModels\WelcomeViewModel.cs:line 65
   at System.Threading.Tasks.Task`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at WitturToolsApp.UserInterface.ViewModels.LdapManager.ConnectAsync(String userId, String password) in C:\WitturRepos\IndicatorNumbers\Source\WitturToolsApp\UserInterface\ViewModels\WelcomeViewModel.cs:line 58
   at WitturToolsApp.UserInterface.ViewModels.WelcomeViewModel.Pick() in C:\WitturRepos\IndicatorNumbers\Source\WitturToolsApp\UserInterface\ViewModels\WelcomeViewModel.cs:line 30

Have somebody any idea to resolve this issue?

**Comment by dsbenghe** [comment]
that looks like a classic error of certificate validation - looks like you are connecting via a secure connection and you don't have the certificate setup.
