### ISSUE TITLE
Connection failure in ipv6-only environment

### ISSUE THREAD

**Issue by LukePulverenti** [dsbenghe/Novell.Directory.Ldap.NETStandard#67]
When entering a host name that only accepts ipv6, the following exception is thrown:
`System.ArgumentException: None of the discovered or specified addresses match the socket address family.
	Parameter name: context
	   at Novell.Directory.Ldap.AsyncExtensions.WaitAndUnwrap(Task task, Int32 timeout)
	   at Novell.Directory.Ldap.Connection.connect(String host, Int32 port, Int32 semaphoreId)
	   at Novell.Directory.Ldap.LdapConnection.Connect(String host, Int32 port)`

This is probably a likely culprit:
https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/blob/3729ef3a6c2e2d7154a3bdb7ccb025d3f56a3909/src/Novell.Directory.Ldap.NETStandard/Connection.cs#L558-L560

**Comment by dsbenghe** [comment]
beta4 version should have the fix
